[build.environment]
  NODE_VERSION = "10"

[[redirects]]
  from = "https://discord.fertindo.com"
  to = "https://discord.com/channels/837037537460879370/837057927528579093"
  status = 301
  force = true
